# Generated by Django 5.0 on 2026-01-26 02:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('total_horas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('descripcion_curso', models.TextField()),
                ('entidad_patrocinadora', models.CharField(max_length=100)),
                ('nombre_contacto_auspicia', models.CharField(blank=True, max_length=100)),
                ('telefono_contacto_auspicia', models.CharField(blank=True, max_length=60)),
                ('email_empresa_patrocinadora', models.EmailField(blank=True, max_length=60)),
                ('activar_para_que_se_vea_en_front', models.BooleanField(default=True)),
                ('ruta_certificado', models.FileField(blank=True, null=True, upload_to='certificados/cursos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Curso Realizado',
                'verbose_name_plural': 'Cursos Realizados',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_perfil', models.CharField(blank=True, help_text='Título profesional o descripción', max_length=50)),
                ('perfil_activo', models.BooleanField(default=True, help_text='Activar/desactivar perfil completo')),
                ('apellidos', models.CharField(max_length=60)),
                ('nombres', models.CharField(max_length=60)),
                ('nacionalidad', models.CharField(default='Ecuatoriana', max_length=20)),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=60)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('numero_cedula', models.CharField(help_text='10 dígitos sin guiones', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe tener exactamente 10 dígitos', regex='^\\d{10}$')])),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1)),
                ('estado_civil', models.CharField(choices=[('Soltero/a', 'Soltero/a'), ('Casado/a', 'Casado/a'), ('Divorciado/a', 'Divorciado/a'), ('Viudo/a', 'Viudo/a'), ('Unión Libre', 'Unión Libre')], max_length=50)),
                ('licencia_conducir', models.CharField(blank=True, help_text='Tipo: A, B, C, etc.', max_length=6)),
                ('telefono_convencional', models.CharField(blank=True, max_length=15)),
                ('telefono_fijo', models.CharField(blank=True, max_length=15)),
                ('direccion_trabajo', models.CharField(blank=True, help_text='Dirección principal de trabajo', max_length=50)),
                ('direccion_domiciliaria', models.CharField(blank=True, help_text='Dirección principal de domicilio', max_length=50)),
                ('sitio_web', models.URLField(blank=True, max_length=60)),
                ('email_personal', models.EmailField(blank=True, max_length=254)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_personales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Datos Personales',
                'verbose_name_plural': 'Datos Personales',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Domicilio', 'Domicilio'), ('Trabajo', 'Trabajo'), ('Otra', 'Otra')], max_length=20)),
                ('direccion_completa', models.CharField(max_length=200)),
                ('ciudad', models.CharField(blank=True, max_length=50)),
                ('provincia', models.CharField(blank=True, max_length=50)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('referencia', models.CharField(blank=True, help_text='Referencias para ubicar', max_length=200)),
                ('es_principal', models.BooleanField(default=False, help_text='Dirección principal')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'ordering': ['-es_principal', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_desempenado', models.CharField(max_length=100, verbose_name='Cargo Desempeñado')),
                ('nombre_empresa', models.CharField(max_length=50, verbose_name='Nombre de la Empresa')),
                ('lugar_empresa', models.CharField(blank=True, max_length=50, verbose_name='Ubicación')),
                ('email_empresa', models.EmailField(blank=True, max_length=100)),
                ('sitio_web_empresa', models.URLField(blank=True, max_length=100)),
                ('nombre_contacto_empresarial', models.CharField(blank=True, max_length=100)),
                ('telefono_contacto_empresarial', models.CharField(blank=True, max_length=60)),
                ('fecha_inicio_gestion', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin_gestion', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('actualmente_trabajando', models.BooleanField(default=False)),
                ('descripcion_funciones', models.TextField(verbose_name='Descripción de Funciones')),
                ('activar_para_que_se_vea_en_front', models.BooleanField(default=True, verbose_name='Mostrar en CV Público')),
                ('ruta_certificado', models.FileField(blank=True, null=True, upload_to='certificados/laborales/', verbose_name='Certificado Laboral')),
                ('orden', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias_laborales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Experiencia Laboral',
                'verbose_name_plural': 'Experiencias Laborales',
                'ordering': ['-fecha_inicio_gestion'],
            },
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado'), ('experto', 'Experto')], max_length=20)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('activar_para_que_se_vea_en_front', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
            },
        ),
        migrations.CreateModel(
            name='ProductoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_recurso', models.CharField(max_length=100)),
                ('clasificador', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('url_publicacion', models.URLField(blank=True)),
                ('activar_para_que_se_vea_en_front', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_academicos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto Académico',
                'verbose_name_plural': 'Productos Académicos',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='ProductoLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('fecha_producto', models.DateField()),
                ('descripcion', models.TextField()),
                ('empresa_relacionada', models.CharField(blank=True, max_length=100)),
                ('url_producto', models.URLField(blank=True)),
                ('activar_para_que_se_vea_en_front', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_laborales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto Laboral',
                'verbose_name_plural': 'Productos Laborales',
                'ordering': ['-fecha_producto'],
            },
        ),
        migrations.CreateModel(
            name='Reconocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reconocimiento', models.CharField(choices=[('Académico', 'Académico'), ('Público', 'Público'), ('Privado', 'Privado')], max_length=100)),
                ('fecha_reconocimiento', models.DateField()),
                ('descripcion_reconocimiento', models.TextField()),
                ('entidad_patrocinadora', models.CharField(max_length=100)),
                ('nombre_contacto_auspicia', models.CharField(blank=True, max_length=100)),
                ('telefono_contacto_auspicia', models.CharField(blank=True, max_length=60)),
                ('activar_para_que_se_vea_en_front', models.BooleanField(default=True)),
                ('ruta_certificado', models.FileField(blank=True, null=True, upload_to='certificados/reconocimientos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconocimientos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reconocimiento',
                'verbose_name_plural': 'Reconocimientos',
                'ordering': ['-fecha_reconocimiento'],
            },
        ),
        migrations.CreateModel(
            name='VentaGarage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('estado_producto', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=40)),
                ('descripcion', models.TextField()),
                ('valor_del_bien', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('foto_producto', models.ImageField(blank=True, null=True, upload_to='garage/')),
                ('activar_para_que_se_vea_en_front', models.BooleanField(default=True)),
                ('vendido', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_garage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta Garage',
                'verbose_name_plural': 'Ventas Garage',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
