# Generated by Django 5.0 on 2026-01-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='github_url',
            field=models.URLField(blank=True, verbose_name='GitHub'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='portfolio_url',
            field=models.URLField(blank=True, verbose_name='Portafolio Personal'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='twitter_url',
            field=models.URLField(blank=True, verbose_name='Twitter/X'),
        ),
    ]
