# Generated by Django 5.0 on 2026-02-01 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_educacion', models.CharField(choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria/Bachillerato'), ('tecnico', 'Técnico/Tecnólogo'), ('tercer_nivel', 'Tercer Nivel (Licenciatura/Ingeniería)'), ('especializacion', 'Especialización'), ('maestria', 'Maestría'), ('doctorado', 'Doctorado/PhD'), ('curso', 'Curso/Certificación'), ('diplomado', 'Diplomado')], max_length=50, verbose_name='Nivel de Educación')),
                ('titulo_obtenido', models.CharField(help_text='Ej: Bachiller en Ciencias, Ingeniero en Sistemas, Master en IA', max_length=150, verbose_name='Título o Certificación Obtenida')),
                ('institucion', models.CharField(help_text='Nombre de la escuela, colegio, universidad o instituto', max_length=150, verbose_name='Institución Educativa')),
                ('fecha_inicio', models.DateField(help_text='Mes y año en que iniciaste', verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, help_text='Déjalo vacío si aún estás estudiando', null=True, verbose_name='Fecha de Finalización')),
                ('actualmente_estudiando', models.BooleanField(default=False, help_text='Marca esta opción si aún continúas estudiando', verbose_name='Actualmente estudiando aquí')),
                ('estado_estudio', models.CharField(choices=[('culminado', 'Culminado'), ('en_curso', 'En Curso'), ('inconcluso', 'Inconcluso')], default='culminado', max_length=20, verbose_name='Estado del Estudio')),
                ('area_estudio', models.CharField(blank=True, help_text='Ej: Tecnología, Salud, Administración, Arte', max_length=100, verbose_name='Área de Estudio')),
                ('ciudad', models.CharField(blank=True, help_text='Ciudad donde estudiaste', max_length=100, verbose_name='Ciudad')),
                ('pais', models.CharField(default='Ecuador', max_length=100, verbose_name='País')),
                ('descripcion', models.TextField(blank=True, help_text='Materias destacadas, proyectos, logros académicos', verbose_name='Descripción')),
                ('calificacion_promedio', models.CharField(blank=True, help_text='Ej: 9.5/10, Cum Laude, Sobresaliente', max_length=50, verbose_name='Calificación/Promedio')),
                ('activar_para_que_se_vea_en_front', models.BooleanField(default=True, verbose_name='Mostrar en CV público')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Educación',
                'verbose_name_plural': 'Educaciones',
                'ordering': ['fecha_inicio'],
            },
        ),
    ]
