# Generated by Django 5.0 on 2026-02-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_educacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='nivel_educacion',
            field=models.CharField(blank=True, choices=[('sin_estudios', 'Sin estudios formales'), ('primaria_incompleta', 'Primaria incompleta'), ('primaria_completa', 'Primaria completa'), ('secundaria_incompleta', 'Secundaria incompleta'), ('bachiller', 'Bachiller'), ('tecnico', 'Técnico/Tecnólogo'), ('universitario_incompleto', 'Universitario incompleto'), ('tercer_nivel', 'Tercer Nivel (Licenciatura/Ingeniería)'), ('cuarto_nivel', 'Cuarto Nivel (Especialización)'), ('maestria', 'Maestría'), ('doctorado', 'Doctorado/PhD')], default='', help_text='Máximo nivel educativo alcanzado', max_length=50, verbose_name='Nivel de Educación'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='titulo_profesional',
            field=models.CharField(blank=True, default='', help_text='Título que aparecerá debajo de tu nombre en el CV (ej: "Ingeniero en Sistemas", "Ama de Casa")', max_length=80, verbose_name='Título Profesional'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='descripcion_perfil',
            field=models.TextField(blank=True, help_text='Descripción amplia sobre ti (varios párrafos permitidos)'),
        ),
    ]
