# Generated by Django 5.0 on 2026-02-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_datospersonales_nivel_educacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='facebook_url',
            field=models.URLField(blank=True, default='', verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='instagram_url',
            field=models.URLField(blank=True, default='', verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='whatsapp_numero',
            field=models.CharField(blank=True, default='', help_text='Número con código de país, ej: +593987654321', max_length=20, verbose_name='Número WhatsApp'),
        ),
    ]
