# Generated by Django 5.0 on 2026-02-01 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_datospersonales_facebook_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Educacion',
        ),
    ]
